config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pictures#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :pictures do
    collection do
    post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  validates :title, :comment, :photos_url, presence: true

  mount_uploader :photos_url, PhotosUploader

  belongs_to :user

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  prepend_before_action :authenticate_user!
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.limit(15).order("updated_at desc")
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
      @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  def confirm
    @picture = Picture.new(picture_params)
    render 'new' if @picture.invalid?
  end
  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_path }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, notice: "投稿できませんでした" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    if @picture.update(picture_params)
      redirect_to @picture, notice: '写真を投稿しました！'
    else
      render 'edit'
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '写真を削除しました！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :comment, :photos_url, :photos_url_cache)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper

  def choose_new_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end


end

app/views/pictures/_form.html.erb
  <div class="row">
    <div class="text-center col-sm-4 col-sm-offset-4">
      <%= form_for(@picture, url: choose_new_edit) do |f| %>
        <%= f.error_messages! %>

        <div class="field form-inline">
          <%= f.label :title, class: "sr-only" %>
          <%= f.text_field :title, placeholder: "タイトル", class: "form-control" %>
        </div><br />
        <div class="field form-inline">
          <%= f.label :comment, class: "sr-only" %>
          <%= f.text_field :comment, placeholder: "コメント", class: "form-control" %>
        </div><br />
        <div class="field form-inline">
          <%= f.hidden_field :photos_url_cache %>
          <%= f.file_field :photos_url, class: "center-block fileupbtn" %>
        </div><br />
        <div class="actions form-inline">
          <%= f.submit "Posting", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>

app/views/pictures/confirm.html.erb
<section class="container" id="confirm">
  <div class="row">
    <h1 class="confirm text-center col-sm-4 col-sm-offset-4">
      <span id="postingconfirm" style="font-family:Billabong">Comfirm Posting</span>
    </h1>
  </div>

  <div class="row">
    <div class="postingcomfirm col-sm-4 col-sm-offset-4">
      <%= form_for(@picture) do |p| %>
        <%= p.hidden_field :title %>
        <%= p.hidden_field :comment %>
        <%= p.hidden_field :photos_url_cache %>
        <h3 class="text-center"><%= @picture.title %></h3><br />
        <div class="compic">
        <%= image_tag(@picture.photos_url, class: "comimg center-block")%><br />
        </div><br />
        <%= @picture.comment%><br />
        <div class="postingconfirmbutton">
          <%= p.submit "Posting!", class: "btn btn-primary center-block" %>
        </div>
      <% end %>
      <br />

      <%= form_for(@picture, url:new_picture_path, method: 'get') do |p| %>
        <% p.hidden_field :title %>
        <% p.hidden_field :comment %>
        <% image_tag(p.hidden_field :photos_url) %>
        <%= p.submit "Back", name: 'back', class: "btn btn-default center-block" %>
      <% end %>
    </div>


  </div>
</section>

app/views/pictures/edit.html.erb
<section div="container">
  <div class="row">
    <div class="text-center col-sm-4 col-sm-offset-4">
      <h1 id="editingpic" style="font-family:Billabong">Edit picture</h1>
    </div>
  </div>

  <%= render 'form'%><br />

  <div class="row">
    <div class="text-center col-sm-4 col-sm-offset-4">
      <%= link_to 'Back to Index', pictures_path, class: "btn btn-default" %>
      <%= link_to 'Show', @picture, class: "btn btn-default" %>
    </div>
  </div>
</section>

app/views/pictures/index.html.erb
<section class="index container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h1 class="text-center"style="font-family:Billabong">Samplegram's pictures</h1>
      <h3 class="bg-info text-center", id="noticemsg"><%= notice %></h3>
    </div>
  </div>
  <div class="row">
    <div class="newpic text-center col-sm-4 col-sm-offset-4 ">
      <%= link_to "Let's Post New Picture!", new_picture_path, class: "new-picture btn btn-default" %>
    </div>
  </div><br />
    <% @pictures.each do |p| %>
    <div class="each-posting col-sm-3 col-md-moffset-1">
      <div class="lists">
        <div class="username usertitle">
          <%= profile_img(p.user) %>
          <%= p.user.name %><br />
          <div class="ptitle">
            <%= p.title %>
          </div>
        </div>
        <div class="pimg">
          <%= link_to image_tag(p.photos_url, class: "tpimg center-block"), picture_path(p), class: "anker" %>
        </div>
        <div class="pcomment">
          <%= p.comment %>
        </div>
        <div class="li buttoms">
          <%= link_to 'Edit', edit_picture_path(p), class: "btn btn-default" %>
          <%= link_to 'Delete', p, class: "btn btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
          <br />
        </div>
      </div>
    </div>
    <% end %>

</section>

app/views/pictures/new.html.erb
<section class="container">
  <div class="row">
    <div class="text-center col-sm-4 col-sm-offset-4">
      <h1 id="postingnew" style="font-family:Billabong">Posting New Picture</h1>
    </div>
  </div>

  <%= render 'form' %><br />

  <div class='row'>
    <div class="text-center col-sm-4 col-sm-offset-4">
    <%= link_to 'Index', pictures_path, class: "btn btn-default" %>
    </div>
  </div>
</section>

app/views/pictures/show.html.erb
<section class="showpage container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h3 class="bg-success text-center"><%= notice %></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="lists">
        <div class="username usertitle">
          <%= profile_img(@picture.user) %>
          <%= @picture.user.name %><br />
          <div class="ptitle">
            <%= @picture.title %>
          </div>
        </div>
        <div class="pimg">
          <%= image_tag(@picture.photos_url, class: "showimg center-block") %>
        </div>
        <div class="pcomment">
          <%= @picture.comment %>
        </div><br />
        <div class="buttomc center-block">
          <%= link_to 'Index', pictures_path, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_picture_path(@picture), class: "btn btn-default" %>
          <%= link_to 'Delete', @picture, class: "btn btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
</section>