config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pictures#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :pictures do
    collection do
    post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Samplegram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="cantainer">
      <div class="navber-header">
        <%= link_to "Samplegram", pictures_path, class: "navbar-brand home", style:"font-family:Billabong" %>
        <div class="currentuser navbar-right">
        <% if user_signed_in? %>
          <%= link_to "マイページ", edit_user_registration_path, class: "navbar-brand mypage" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-brand logout" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "navbar-brand login" %>
          <%= link_to "サインアップ", new_user_registration_path, class: "navbar-brand signup" %>
        <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

<%= yield %>

<nav class="navbar navbar-default navbar-fixed-bottom">
  <footer>
    <p id="footer">@ 2017 Copyright Syareotu Corp.</p>
  </footer>
</nav>
</body>
</html>